### ISSUE TITLE
merge into MLDatasets?

### ISSUE THREAD

**Issue by CarloLucibello** [lorenzoh/DLDatasets.jl#1]
Hi, 
there is a lot of nice work here, would you consider merging it into [MLDatasets.jl](https://github.com/JuliaML/MLDatasets.jl)?
We have recently removed datasets from Flux and point users to MLDatasets.jl, it would be nice to have a central repository there.

**Comment by CarloLucibello** [comment]
bump on this. I can move over the code
(I wouldn't do anything more than a copy and paste, homogenization can come later)
although is better if @lorenzoh does it to preserve authorship

cc @johnnychen94  @darsnack

**Comment by lorenzoh** [comment]
Might be better to move the datasets code from https://github.com/lorenzoh/FastAI.jl/tree/master/src/datasets into MLDatasets.jl as it currently supports more datasets already, what do you think?

DLDatasets.jl has some pose estimation datasets which could be ported over, though one of them depends on `PyCall` which is a big dependency.

I can get a pull request started over the next few days 👍
